# Generated by Django 5.1.1 on 2025-01-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='date',
            field=models.DateField(default='2025-01-01'),
        ),
    ]
